In [10]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [11]:
df1 = pd.read_excel("Rhein_Rekingen_34.xlsx", sheet_name='Sammelproben K')
df2 = pd.read_excel("Rhein_Laufenburg_08.xlsx", sheet_name='Sammelproben K')
df3 = pd.read_excel("Rhein_Diepoldsau_34.xlsx", sheet_name='Sammelproben K')
df4 = pd.read_excel("Rhein_Rheinfelden_08.xlsx", sheet_name='Sammelproben K')
df5 = pd.read_excel("Rhein_Schmitter_10.xlsx", sheet_name='Sammelproben K')
df6 = pd.read_excel("Rhein_Village-Neuf_10.xlsx", sheet_name='Sammelproben K')
df7 = pd.read_excel("Rhein_Weil_Jahrbuch_29.xlsx", sheet_name='Sammelproben K')

In [12]:
#cutting off frist explanatory row
df1=df1.iloc[1:]
df2=df2.iloc[1:]
df3=df3.iloc[1:]
df4=df4.iloc[1:]
df5=df5.iloc[1:]
df6=df6.iloc[1:]
df7=df7.iloc[1:]

In [13]:
#add value of river kilometers
df1 = df1.assign(Rheinkilometer='90')
df2 = df2.assign(Rheinkilometer='122')
df3 = df3.assign(Rheinkilometer='0')
df4 = df4.assign(Rheinkilometer='150')
df5 = df5.assign(Rheinkilometer='0')
df6 = df6.assign(Rheinkilometer='173')
df7 = df7.assign(Rheinkilometer='170')

In [14]:
#append frames to one 
dfx = df1.append(df2, ignore_index=True, sort=False)
dfx = dfx.append(df3, ignore_index=True, sort=False)
dfx = dfx.append(df4, ignore_index=True, sort=False)
dfx = dfx.append(df5, ignore_index=True, sort=False)

In [15]:
# combine station names DI and SC to DI
dfx.replace(['SC'],["DI"])

,Kürzel,Status Nr.,Bemerkung,Labornummer,Jahr,Datum,Dauer,Mittl.Abfluss,Abflussumme,Temp.(BAFU),...,Blei,Nickel,Quecksilber,NP,NP1EO,NP2EO,NP3EO,Calcium (IC),Rheinkilometer,Status Nr.
0,RE,7,NaN,16354,1975.0,1975-05-26 11:15:00,168.0,NaN,NaN,NaN,...,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
1,RE,1,NaN,16487,1975.0,1975-06-02 11:45:00,169.0,683.00,415.5372,13.70,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
2,RE,4,Pb unsicher: Wartung oder Beginn von Hochwasser?,16619,1975.0,1975-06-09 10:40:00,167.0,680.00,408.8160,13.40,...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
3,RE,1,NaN,16705,1975.0,1975-06-16 11:20:00,169.0,609.00,370.5156,14.90,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
4,RE,1,NaN,16843,1975.0,1975-06-23 13:30:00,170.0,735.00,449.8200,14.40,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
5,RE,2,Problem mit Schöpfbecher,16892,1975.0,1975-06-30 13:30:00,168.0,853.00,515.8944,15.50,...,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
6,RE,1,NaN,16991,1975.0,1975-07-07 12:20:00,167.0,947.00,569.3364,15.10,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
7,RE,1,NaN,17115,1975.0,1975-07-14 10:15:00,166.0,879.00,525.2904,17.30,...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
8,RE,1,NaN,17203,1975.0,1975-07-21 12:20:00,170.0,894.00,547.1280,18.30,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
9,RE,2,Flasche überlaufen 0.5l,17219,1975.0,1975-07-28 11:10:00,167.0,869.00,522.4428,18.00,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
10,RE,1,NaN,17232,1975.0,1975-08-04 10:00:00,167.0,770.00,462.9240,19.10,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
11,RE,9,Probe gefroren,17266,1975.0,1975-08-11 10:00:00,168.0,660.00,399.1680,21.10,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
12,RE,1,NaN,17305,1975.0,1975-08-18 14:00:00,172.0,722.00,447.0624,19.80,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
13,RE,1,NaN,17392,1975.0,1975-08-25 11:00:00,165.0,811.00,481.7340,18.20,...,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
14,RE,1,NaN,17433,1975.0,1975-09-01 10:15:00,167.0,890.00,535.0680,16.90,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
15,RE,1,NaN,17495,1975.0,1975-09-08 10:10:00,168.0,757.00,457.8336,18.00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
16,RE,1,NaN,17593,1975.0,1975-09-15 13:30:00,171.0,698.00,429.6888,17.50,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
17,RE,1,NaN,17618,1975.0,1975-09-22 12:30:00,167.0,629.00,378.1548,17.60,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
18,RE,1,NaN,17664,1975.0,1975-09-29 11:30:00,167.0,566.00,340.2792,17.40,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
19,RE,1,NaN,17750,1975.0,1975-10-06 14:20:00,171.0,501.00,308.4156,17.00,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
20,RE,1,NaN,17780,1975.0,1975-10-13 10:50:00,165.0,422.00,250.6680,15.50,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
21,RE,1,NaN,17796,1975.0,1975-10-20 11:00:00,168.0,403.00,243.7344,13.10,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
22,RE,1,NaN,17901,1975.0,1975-10-27 10:00:00,167.0,391.00,235.0692,11.90,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
23,RE,1,NaN,17951,1975.0,1975-11-03 12:20:00,170.0,325.00,198.9000,11.10,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
24,RE,1,NaN,17992,1975.0,1975-11-10 14:00:00,170.0,287.00,175.6440,10.80,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
25,RE,1,NaN,18047,1975.0,1975-11-17 14:00:00,168.0,287.00,173.5776,10.00,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
26,RE,1,NaN,18071,1975.0,1975-11-24 10:45:00,165.0,419.00,248.8860,8.10,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
27,RE,1,NaN,18099,1975.0,1975-12-01 10:30:00,168.0,341.00,206.2368,7.30,...,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
28,RE,1,NaN,18146,1975.0,1975-12-08 10:45:00,168.0,341.00,206.2368,6.70,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
29,RE,1,NaN,18179,1975.0,1975-12-15 11:15:00,169.0,298.00,181.3032,6.10,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3083,DI,NaN,NaN,38397,1983.0,1983-06-27 09:15:00,335.0,522.80,631.4700,9.77,...,NaN,NaN,NaN,4.0325,0.5,0.5,NaN,NaN,0,1
3084,DI,NaN,NaN,38440,1983.0,1983-07-11 10:05:00,337.0,491.30,595.7600,11.00,...,NaN,NaN,NaN,4.3036,0.5,0.5,NaN,NaN,0,1
3085,DI,NaN,NaN,38496,1983.0,1983-07-25 09:30:00,335.0,401.10,484.3400,12.44,...,NaN,NaN,NaN,3.9000,0.5,0.5,NaN,NaN,0,1
3086,DI,NaN,NaN,38513,1983.0,1983-08-08 09:50:00,336.0,337.60,408.7800,11.97,...,NaN,NaN,NaN,2.6832,0.5,0.5,NaN,NaN,0,1
3087,DI,NaN,NaN,38547,1983.0,1983-08-22 10:00:00,336.0,220.90,267.3200,12.57,...,NaN,NaN,NaN,2.3668,0.5,0.5,NaN,NaN,0,1
3088,DI,NaN,NaN,38618,1983.0,1983-09-05 09:50:00,336.0,216.50,261.7800,12.86,...,NaN,NaN,NaN,2.3975,0.5,0.5,NaN,NaN,0,1
3089,DI,NaN,NaN,38675,1983.0,1983-09-19 09:30:00,336.0,402.60,486.5000,10.40,...,NaN,NaN,NaN,1.4540,0.5,0.5,NaN,NaN,0,1
3090,DI,NaN,NaN,38707,1983.0,1983-10-03 09:50:00,336.0,231.00,279.6500,10.71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1
3091,DI,NaN,NaN,38738,1983.0,1983-10-17 09:30:00,336.0,158.10,191.0800,9.91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1
3092,DI,NaN,NaN,38754,1983.0,1983-10-31 09:40:00,336.0,137.10,165.8800,7.74,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1
3093,DI,NaN,NaN,38805,1983.0,1983-11-14 09:40:00,336.0,113.20,136.9800,7.05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1
3094,DI,NaN,NaN,38830,1983.0,1983-11-28 09:50:00,336.0,129.40,156.5900,4.95,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1
3095,DI,NaN,NaN,38943,1983.0,1983-12-12 10:00:00,336.0,131.20,158.7700,3.67,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1
3096,DI,NaN,NaN,39050,1983.0,1983-12-27 09:50:00,360.0,132.70,171.8600,4.28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1
3097,DI,NaN,"Zeit?, physikalische Parameter müssen beim BAF...",39063,1984.0,1984-01-09 10:00:00,312.0,110.36,123.9600,4.17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,"6,7"
3098,DI,NaN,Unterbruch 12.1.84 14:00 bis 13.1.84 14:00; 2....,39085,1984.0,1984-01-23 09:50:00,336.0,111.50,134.7700,3.20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,"2,6,7"
3099,DI,NaN,"Zeit?, physikalische Parameter müssen beim BAF...",39178,1984.0,1984-02-06 10:00:00,336.0,104.14,126.0300,3.69,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,"6,7"
3100,DI,NaN,"Zeit?, physikalische Parameter müssen beim BAF...",39303,1984.0,1984-02-20 10:20:00,336.0,124.39,150.5700,2.56,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,"6,7"
3101,DI,NaN,"Zeit?, physikalische Parameter müssen beim BAF...",39332,1984.0,1984-03-05 10:10:00,336.0,120.07,145.0900,3.58,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,"6,7"
3102,DI,NaN,"Zeit?, physikalische Parameter müssen beim BAF...",39358,1984.0,1984-03-19 10:15:00,336.0,119.22,144.3200,4.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,"6,7"
3103,DI,NaN,"keine Probe; Zeit?, physikalische Parameter mü...",39431,1984.0,1984-04-02 10:00:00,336.0,119.23,144.2900,5.72,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,"3,6,7"
3104,DI,NaN,keine Probe,1984,1984.0,1984-04-16 10:00:00,336.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
3105,DI,NaN,keine Probe,1984,1984.0,1984-04-30 10:00:00,336.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
3106,DI,NaN,keine Probe,1984,1984.0,1984-05-14 10:00:00,336.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
3107,DI,NaN,keine Probe,1984,1984.0,1984-05-28 10:00:00,336.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
3108,DI,NaN,keine Probe,1984,1984.0,1984-06-11 10:00:00,336.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
3109,DI,NaN,wahrscheinlich nur über 2. Woche gesammelt; Ze...,39714,1984.0,1984-06-25 09:25:00,312.0,543.16,610.2300,9.40,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,"3,6,7"
3110,DI,NaN,"Zeit?, physikalische Parameter müssen beim BAF...",39746,1984.0,1984-07-09 09:05:00,336.0,465.63,562.9500,9.63,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,"6,7"
3111,DI,NaN,"Zeit?, physikalische Parameter müssen beim BAF...",39792,1984.0,1984-07-23 09:40:00,337.0,378.40,458.5000,11.36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,"6,7"
3112,DI,NaN,"Zeit?, physikalische Parameter müssen beim BAF...",39840,1984.0,1984-08-06 10:05:00,336.0,287.50,348.0100,11.96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,"6,7"

In [16]:
#set row for year, month and day 
dfx['Datum'] = pd.to_datetime(dfx['Datum'])
dfx['year'] = dfx['Datum'].dt.year
dfx['month'] = dfx['Datum'].dt.month
dfx['day'] = dfx['Datum'].dt.day

In [17]:
#delete colum with comments

del dfx['Bemerkung']

#objetcs to floats
cols = dfx.columns.drop('Kürzel','Datum')
dfx[cols] = dfx[cols].apply(pd.to_numeric, errors='coerce')

#keep datetimeindex
dfx['Datum'] = pd.to_datetime(dfx['Datum'])

In [18]:
#export complete frame as csv
dfx.to_csv("data_rhein_incl_km.csv")
dfx.to_excel("data_rhein_incl_km.xlsx")